image: "redoxos/redoxer:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get install nasm
  - rustup component add rust-src

stages:
  - build

  # TODO?
  # - test

build:x86_64:
  stage: build
  script:
    - mkdir -p target/x86_64
    - make ARCH=x86_64 BUILD=target/x86_64

build:i686:
  stage: build
  script:
    - mkdir -p target/i686
    - make ARCH=i686 BUILD=target/i686

build:aarch64:
  stage: build
  script:
    - mkdir -p target/aarch64
      # TODO: cross compiler binutils?
    - make target/aarch64/kernel.all ARCH=aarch64 BUILD=target/aarch64

fmt:
    stage: build
    needs: []
    script:
        - rustup component add rustfmt-preview
        - cargo fmt -- --check

# TODO: unit tests
