image: "redoxos/redoxer:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get install nasm
  - rustup component add rust-src

stages:
  - host
  # TODO: redoxer test
  # TODO: benchmarks and profiling (maybe manually enabled for relevant MRs)?

build:x86_64:
  stage: host
  script:
    - mkdir -p target/x86_64
    - make ARCH=x86_64 BUILD=target/x86_64

build:i686:
  stage: host
  script:
    - mkdir -p target/i686
    - make ARCH=i686 BUILD=target/i686

build:aarch64:
  stage: host
  script:
    - mkdir -p target/aarch64
      # TODO: cross compiler binutils?
    - make target/aarch64/kernel.all ARCH=aarch64 BUILD=target/aarch64
  allow_failure: true

fmt:
  stage: host
  script:
      - rustup component add rustfmt-preview
      - cargo fmt -- --check

unit_test:
  stage: host
  script:
    - cargo test
