[package]
name = "kernel"
version = "0.1.54"
build = "build.rs"
edition = "2018"

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.2.1"
linked_list_allocator = "0.8.4"
raw-cpuid = "8.0.0"
redox_syscall = { path = "syscall" }
slab_allocator = { path = "slab_allocator", optional = true }
spin = "0.5.2"
paste = "0.1.18"

[dependencies.goblin]
version = "0.2.1"
default-features = false
features = ["elf32", "elf64"]

[dependencies.rustc-demangle]
version = "0.1.16"
default-features = false

[dependencies.x86]
version = "0.29.0"
default-features = false

[features]
default = ["acpi", "multi_core", "serial_debug"]
acpi = []
doc = []
graphical_debug = []
live = []
lpss_debug = []
multi_core = ["acpi"]
pti = []
qemu_debug = []
serial_debug = []
slab = ["slab_allocator"]
